version: '3'

services:
  vitty-api:
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/user/src/app
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
volumes:
  postgres-db:
